jobs:
    check-format:
        container: node:13
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install Dependencies
              run: npm ci

            - name: Check Format
              run: npm run check
name: Format
on: [pull_request, push]
